name: Upload SBOM to Dependency-Track

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/sbom.yaml
  workflow_dispatch:

jobs:
  generate_and_upload:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3.5.3

      - uses: docker/setup-buildx-action@v2.2.1

      - uses: docker/build-push-action@v6.9.0
        with:
          context: .
          load: true
          tags: simonknittel/rtmp-server:master

      - uses: anchore/sbom-action@v0.13.1
        with:
          image: simonknittel/rtmp-server:master
          artifact-name: sbom.cdx.json
          output-file: sbom.cdx.json
          format: cyclonedx-json

      - uses: DependencyTrack/gh-upload-sbom@master
        with:
          serverhostname: ${{ secrets.DTRACK_SERVERHOSTNAME }}
          apikey: ${{ secrets.DTRACK_APIKEY }}
          project: ${{ secrets.DTRACK_PROJECT }}
          bomfilename: sbom.cdx.json

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: sbom.cdx.json
          path: sbom.cdx.json
